[project]
name = "tabla-sitar-seperation"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10.6"
dependencies = [
    "demucs>=4.0.1",
    "librosa>=0.11.0",
    "soundfile>=0.13.1",
    "streamlit>=1.54.0",
    "torchcodec>=0.10.0",
]
